/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary": "#006058",
        "on-primary-fixed-variant": "#003ea8",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary-fixed": "#00201d",
        "on-error-container": "#93000a",
        "primary": "#004ac6",
        "inverse-primary": "#b4c5ff",
        "secondary-fixed": "#c9e6ff",
        "on-surface-variant": "#434655",
        "on-surface": "#0b1c30",
        "on-tertiary-fixed-variant": "#005049",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "surface-container-low": "#eff4ff",
        "tertiary-container": "#007b71",
        "secondary": "#006591",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-fixed": "#00174b",
        "surface-tint": "#0053db",
        "surface-dim": "#cbdbf5",
        "on-secondary-container": "#004666",
        "on-primary-container": "#eeefff",
        "inverse-surface": "#213145",
        "primary-container": "#2563eb",
        "on-secondary-fixed-variant": "#004c6e",
        "on-secondary-fixed": "#001e2f",
        "secondary-fixed-dim": "#89ceff",
        "surface-variant": "#d3e4fe",
        "primary-fixed-dim": "#b4c5ff",
        "secondary-container": "#39b8fd",
        "tertiary-fixed": "#89f5e7",
        "background": "#f8f9ff",
        "surface-container-high": "#dce9ff",
        "surface": "#f8f9ff",
        "outline-variant": "#c3c6d7",
        "surface-container": "#e5eeff",
        "tertiary-fixed-dim": "#6bd8cb",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "on-background": "#0b1c30",
        "outline": "#737686",
        "on-tertiary-container": "#b3fff3",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "container-max": "1440px",
        unit: "4px",
        "margin-desktop": "32px",
        gutter: "24px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "title-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "title-md": ["Inter"],
        "body-sm": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
